######################################################################
# Copyright 2016, 2024 John J. Rofrano. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
######################################################################
# pylint: disable=function-redefined, missing-function-docstring
# flake8: noqa

"""
Wishlist Steps

Steps file for Wishlist.feature

For information on Waiting until elements are present in the HTML see:
    https://selenium-python.readthedocs.io/waits.html
"""
from pathlib import Path
import os
import requests
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from behave import given, when, then  # pylint: disable=no-name-in-module


# HTTP Return Codes
HTTP_200_OK = 200
HTTP_201_CREATED = 201
HTTP_204_NO_CONTENT = 204

WAIT_TIMEOUT = 60


def load_api_key():
    """Load API key generated by the service at startup."""
    key_file = Path("apikey.txt")
    if key_file.exists():
        return key_file.read_text(encoding="utf-8").strip()
    raise RuntimeError(
        "API Key file not found! The service may not be running or the key was not generated."
    )


API_KEY = load_api_key()


@given("the Flask wishlist service is running")
def step_impl(context):
    """Start a Chrome browser and open the app"""
    options = webdriver.ChromeOptions()
    options.add_argument("--headless")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")

    context.driver = webdriver.Chrome(options=options)
    # print("DEBUG >>> ENV BASE_URL =", os.getenv("BASE_URL"))
    context.base_url = os.getenv("BASE_URL", "http://localhost:8080")
    # context.base_url = "http://localhost:8080"


@given(
    'an item exists in wishlist with product_id "{product_id}" named "{name}" with price "{price}"'
)
def step_impl(context, product_id, name, price):
    """Create an item in the current wishlist via the API."""
    assert hasattr(context, "created_wishlist_id"), "No wishlist created yet."

    payload = {
        "product_id": int(product_id),
        "product_name": name,
        "price": float(price),
    }
    response = requests.post(
        f"{context.base_url}/api/wishlists/{context.created_wishlist_id}/items",
        json=payload,
        headers={"Content-Type": "application/json"},
        timeout=WAIT_TIMEOUT,
    )
    assert (
        response.status_code == HTTP_201_CREATED
    ), f"Failed to create item: {response.status_code} {response.text}"

    # Save the created item and its ID to context
    context.created_item = response.json()
    context.created_item_id = context.created_item.get("id")
    assert context.created_item_id, "Item id was not returned by the service."


@when("I copy the created wishlist id into the wishlist field")
def step_impl(context):
    """Populate the wishlist ID field with the previously created wishlist."""
    assert (
        hasattr(context, "created_wishlist_id") and context.created_wishlist_id
    ), "No wishlist id is available in context."
    element = context.driver.find_element(By.ID, "wishlist_id")
    element.clear()
    element.send_keys(str(context.created_wishlist_id))


@then('neither "{wishlist_name}" nor "{item_name}" should appear in the list')
def step_impl(context, wishlist_name, item_name):

    name_input = context.driver.find_element(By.ID, "wishlist_wishlist_name")
    name_input.clear()
    name_input.send_keys(wishlist_name)

    search_btn = context.driver.find_element(By.ID, "search_wishlists-btn")
    search_btn.click()

    table = context.driver.find_element(
        By.CSS_SELECTOR, "#search_results table.table-striped"
    )

    tbodys = table.find_elements(By.TAG_NAME, "tbody")
    text = ""
    if tbodys:
        text = tbodys[0].text

    assert (
        wishlist_name not in text
    ), f'Unexpectedly found wishlist "{wishlist_name}" in results.'
    assert item_name not in text, f'Unexpectedly found item "{item_name}" in results.'


@when('I click the "Delete Wishlist" button')
def step_impl(context):
    btn = context.driver.find_element(By.ID, "delete_wishlist-btn")
    btn.click()

    try:
        WebDriverWait(context.driver, 5).until(
            EC.text_to_be_present_in_element((By.ID, "flash_message"), "deleted")
        )
    except Exception:
        pass


@when("I copy the created wishlist id into the wishlist form")
def step_impl(context):
    """Open Home Page and fill the wishlist id field with the created id."""
    assert (
        hasattr(context, "created_wishlist_id") and context.created_wishlist_id
    ), "No wishlist id found in context. You must create one first."

    context.driver.get(context.base_url)

    WebDriverWait(context.driver, WAIT_TIMEOUT).until(
        EC.presence_of_element_located((By.TAG_NAME, "body"))
    )
    WebDriverWait(context.driver, WAIT_TIMEOUT).until(
        EC.presence_of_element_located((By.ID, "wishlist_id"))
    )

    element = context.driver.find_element(By.ID, "wishlist_id")
    element.clear()
    element.send_keys(str(context.created_wishlist_id))


@then('"Temp List" should not appear in the list')
def step_impl(context):
    """Verify that the deleted wishlist no longer appears in the search results"""
    name_input = context.driver.find_element(By.ID, "wishlist_wishlist_name")
    name_input.clear()
    name_input.send_keys("Temp List")

    search_btn = context.driver.find_element(By.ID, "search_wishlists-btn")
    search_btn.click()

    table = context.driver.find_element(
        By.CSS_SELECTOR, "#search_results table.table-striped"
    )

    tbodys = table.find_elements(By.TAG_NAME, "tbody")
    text = tbodys[0].text if tbodys else ""

    assert (
        "Temp List" not in text
    ), 'Unexpectedly found deleted wishlist "Temp List" in results.'


@given('a wishlist named "{name}"')
def step_impl(context, name):
    """Create a wishlist via the API with a default customer ID and navigate to the homepage."""
    customer_id = "CUST-ACTION"

    # First ensure no conflicting wishlist exists
    response = requests.get(
        f"{context.base_url}/api/wishlists",
        params={"customer_id": customer_id, "name": name},
        timeout=WAIT_TIMEOUT,
    )
    assert response.status_code == HTTP_200_OK, (
        f"Failed to query wishlists for cleanup. Status: {response.status_code}, "
        f"Body: {response.text}"
    )
    for wishlist in response.json():
        requests.delete(
            f"{context.base_url}/api/wishlists/{wishlist['id']}",
            headers={"X-Api-Key": API_KEY},
            timeout=WAIT_TIMEOUT,
        )

    # Create the wishlist
    payload = {
        "customer_id": customer_id,
        "name": name,
        "description": f"Wishlist for action testing: {name}",
    }
    response = requests.post(
        f"{context.base_url}/api/wishlists",
        json=payload,
        headers={"Content-Type": "application/json", "X-Api-Key": API_KEY},
        timeout=WAIT_TIMEOUT,
    )
    assert (
        response.status_code == HTTP_201_CREATED
    ), f"Failed to create wishlist: {response.status_code} {response.text}"

    context.created_wishlist = response.json()
    context.created_wishlist_id = context.created_wishlist.get("id")
    assert context.created_wishlist_id, "Wishlist id was not returned by the service."

    # Navigate to the homepage and populate the wishlist ID field
    context.driver.get(context.base_url)
    WebDriverWait(context.driver, WAIT_TIMEOUT).until(
        EC.presence_of_element_located((By.TAG_NAME, "body"))
    )
    WebDriverWait(context.driver, WAIT_TIMEOUT).until(
        EC.presence_of_element_located((By.ID, "wishlist_id"))
    )

    # Fill in the wishlist ID
    element = context.driver.find_element(By.ID, "wishlist_id")
    element.clear()
    element.send_keys(str(context.created_wishlist_id))


@when('I click "{button_text}" for that wishlist')
def step_impl(context, button_text):
    """Click a button identified by its text, for the current wishlist."""
    button_id = button_text.lower().replace(" ", "_") + "_wishlist-btn"
    button = WebDriverWait(context.driver, WAIT_TIMEOUT).until(
        EC.element_to_be_clickable((By.ID, button_id))
    )
    button.click()

    # If this is the Share button, capture the share URL from flash message
    if button_text.lower() == "share":
        # Wait for the flash message to update
        WebDriverWait(context.driver, WAIT_TIMEOUT).until(
            EC.text_to_be_present_in_element((By.ID, "flash_message"), "Share URL")
        )
        # Store the share link for later verification
        flash_element = context.driver.find_element(By.ID, "flash_message")
        links = flash_element.find_elements(By.TAG_NAME, "a")
        if links:
            context.share_url = links[0].get_attribute("href")

    # Wait a moment for the action to complete
    import time

    time.sleep(0.5)


@then("the wishlist link should show")
def step_impl(context):
    """Verify that the share link was captured during the Share action."""
    assert (
        hasattr(context, "share_url") and context.share_url
    ), "No share URL was captured. Make sure the Share button was clicked first."

    assert f"/wishlists/{context.created_wishlist_id}" in context.share_url, (
        f"Share URL does not contain the correct wishlist ID. "
        f"Expected ID: {context.created_wishlist_id}, Got URL: {context.share_url}"
    )


@then("the wishlist should show as empty")
def step_impl(context):
    """Verify that the wishlist has no items by retrieving it and checking the items list."""
    # Retrieve the wishlist to check its items
    retrieve_btn = context.driver.find_element(By.ID, "retrieve_wishlist-btn")
    retrieve_btn.click()

    # Wait for the results to load
    WebDriverWait(context.driver, WAIT_TIMEOUT).until(
        EC.presence_of_element_located((By.ID, "search_results"))
    )

    # Check that the search results show "No items found" or the items table is empty
    search_results = context.driver.find_element(By.ID, "search_results")
    results_text = search_results.text

    # Either "No items found" message should appear, or the table should be empty
    # The retrieve action also fetches items and displays them in the results table
    assert (
        "No items found" in results_text
        or len(search_results.find_elements(By.CSS_SELECTOR, "table tbody tr")) == 0
    ), f"Expected wishlist to be empty, but found items in results: {results_text}"
