apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: GIT_REPO
      type: string
      description: The URL to the git repo
    - name: GIT_REF
      type: string
      description: The reference (branch or ref)
      default: master
    - name: IMAGE_NAME
      type: string
      description: The name of the image to build
      default: wishlists
    - name: IMAGE_TAG
      type: string
      description: The tag for the image
      default: latest

  workspaces:
    - name: pipeline-workspace

  tasks:
    - name: git-clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      params:
        - name: CRT_FILENAME
          value: ca-bundle.crt
        - name: HTTP_PROXY
          value: ""
        - name: HTTPS_PROXY
          value: ""
        - name: NO_PROXY
          value: ""
        - name: SUBDIRECTORY
          value: ""
        - name: USER_HOME
          value: /home/git
        - name: DELETE_EXISTING
          value: "true"
        - name: VERBOSE
          value: "false"
        - name: SSL_VERIFY
          value: "true"
        - name: URL
          value: $(params.GIT_REPO)
        - name: REVISION
          value: $(params.GIT_REF)
        - name: REFSPEC
          value: ""
        - name: SUBMODULES
          value: "true"
        - name: DEPTH
          value: "1"
        - name: SPARSE_CHECKOUT_DIRECTORIES
          value: ""
      workspaces:
        - name: output
          workspace: pipeline-workspace

    # Lint task - Runs flake8 and pylint in parallel with test
    - name: lint
      taskRef:
        name: lint
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: pipeline-workspace

    # Test task - Runs unit tests in parallel with lint
    - name: test
      taskRef:
        name: pytest-env
      runAfter:
        - git-clone
      params:
        - name: pytest-args
          value:
            - "--cov=service"
            - "--cov-fail-under=95"
      workspaces:
        - name: source
          workspace: pipeline-workspace

    # Build task - Runs after both lint and test complete successfully
    - name: build
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
          - name: version
            value: "0.9"
      runAfter:
        - lint
        - test
      params:
        - name: IMAGE
          value: "image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.IMAGE_NAME):$(params.IMAGE_TAG)"
      workspaces:
        - name: source
          workspace: pipeline-workspace
    # Deploy task - Deploys the application to Kubernetes
    - name: deploy
      taskRef:
        name: deploy-image
      runAfter:
        - build
      params:
        - name: image-name
          value: "image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.IMAGE_NAME):$(params.IMAGE_TAG)"
        - name: manifest-dir
          value: "k8s"
      workspaces:
        - name: source
          workspace: pipeline-workspace