apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  params:
    - name: GIT_REPO
      type: string
      description: The URL to the git repo
    - name: GIT_REF
      type: string
      description: The reference (branch or ref)
      default: master
    - name: APP_NAME
      type: string
      description: Name of application
      default: wishlist
    - name: IMAGE_NAME
      type: string
      description: The name of the image to build
      default: "image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.APP_NAME):latest"
    - name: BASE_URL
      type: string
      description: The URL to the wishlist service
    - name: API_KEY
      type: string
      description: The API key to access the wishlist service
      default: "dev-api-key-123"

  workspaces:
    - name: pipeline-workspace

  tasks:
    - name: git-clone
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: namespace
            value: openshift-pipelines
      params:
        - name: CRT_FILENAME
          value: ca-bundle.crt
        - name: HTTP_PROXY
          value: ""
        - name: HTTPS_PROXY
          value: ""
        - name: NO_PROXY
          value: ""
        - name: SUBDIRECTORY
          value: ""
        - name: USER_HOME
          value: /home/git
        - name: DELETE_EXISTING
          value: "true"
        - name: VERBOSE
          value: "false"
        - name: SSL_VERIFY
          value: "true"
        - name: URL
          value: $(params.GIT_REPO)
        - name: REVISION
          value: $(params.GIT_REF)
        - name: REFSPEC
          value: ""
        - name: SUBMODULES
          value: "true"
        - name: DEPTH
          value: "1"
        - name: SPARSE_CHECKOUT_DIRECTORIES
          value: ""
      workspaces:
        - name: output
          workspace: pipeline-workspace

    - name: pytest-env
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: pytest-env
      params:
        - name: pytest-args
          value:
            - "--cov-fail-under=95"
            - "--cov=service"
        - name: secret-name
          value: postgres-creds
        - name: secret-key
          value: database_uri
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: lint
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: lint
      params:
        - name: image
          value: "quay.io/rofrano/python:3.11-slim"
        - name: path
          value: service tests
        - name: requirements-file
          value: requirements.txt
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: buildah
      runAfter:
        - pytest-env
        - lint
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: buildah
          - name: namespace
            value: openshift-pipelines
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: BUILD_ARGS
          value:
            - ""
        - name: CONTEXT
          value: .
        - name: STORAGE_DRIVER
          value: vfs
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: ""
        - name: PUSH_EXTRA_ARGS
          value: ""
        - name: SKIP_PUSH
          value: "false"
        - name: TLS_VERIFY
          value: "true"
        - name: VERBOSE
          value: "false"
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: deploy-image
      runAfter:
        - buildah
      taskRef:
        kind: Task
        name: deploy-image
      params:
        - name: image-name
          value: $(params.IMAGE_NAME)
        - name: manifest-dir
          value: k8s
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: behave
      runAfter:
        - deploy-image
      taskRef:
        kind: Task
        name: behave
      params:
        - name: base-url
          value: $(params.BASE_URL)
        - name: api-key
          value: $(params.API_KEY)
        - name: wait-seconds
          value: "60"
        - name: driver
          value: chrome
      workspaces:
        - name: source
          workspace: pipeline-workspace