apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cd-pipeline
spec:
  to:
    kind: Service
    name: el-cd-listener
    weight: 100
  port:
    targetPort: http-listener
  tls:
    termination: edge
  wildcardPolicy: None