name: CI Build
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.11-slim

    # Required services
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: pgs3cr3t
          POSTGRES_DB: test_db
        # Set health checks to wait until Postgres has started
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    # Steps for the build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python package dependencies
        run: |
          python -m pip install -U pip pipenv
          pipenv install --system --dev
      - name: Linting
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 service tests --count --select=E9,F63,F7,F82 --show-source --statistics
          # test for complexity. The GitHub editor is 127 chars wide
          flake8 service tests --count --max-complexity=10 --max-line-length=127 --statistics
          # Run pylint to catch other PEP8 errors
          pylint service tests --max-line-length=127
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install -y postgresql-client
      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h postgres -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 1
          done
      - name: Create database tables
        run: |
          python -c "
          from service import create_app
          from service.models import db
          from service.models import Wishlist
          from service.models import Item
          
          app = create_app()
          with app.app_context():
              # Drop all tables first to ensure clean state
              db.drop_all()
              # Create all tables
              db.create_all()
              # Verify tables were created
              print('\n=== Database Tables ===')
              print(db.metadata.tables.keys())
              print('======================\n')
              db.session.commit()"
        env:
          FLASK_APP: "service:create_app"
          FLASK_ENV: "testing"
          DATABASE_URI: "postgresql+psycopg://postgres:pgs3cr3t@postgres:5432/test_db"

      - name: Run unit tests with PyTest
        run: |
          pytest --pspec --cov=service --cov-fail-under=95 --cov-report=xml -v
        env:
          FLASK_APP: "service:create_app"
          FLASK_ENV: "testing"
          DATABASE_URI: "postgresql+psycopg://postgres:pgs3cr3t@postgres:5432/test_db"

      ######################################################################
      # Create a CODECOV_TOKEN in Settings->Secrets and variables->Actions
      # and then uncomment the CodeCov action during hands-on lab
      ######################################################################
      - name: Install packages for Codecov to work
        run: apt-get update && apt-get install -y git curl gpg

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: CSCI-GA-2820-003/wishlists